service: dutchie-native
frameworkVersion: '3'

custom:
    environment: ${file(env.yml):${self:provider.stage}, file(env.yml):dev}

provider:
  name: aws
  runtime: nodejs18.x
  stage: prod
  region: us-east-1
  httpApi:
    cors:
      allowedOrigins:
        - 'https://tj-the-revolution-6206508ef5c2d17ee4134.webflow.io'
        - 'https://dev2.terpenejourney.com'
      allowCredentials: true

functions:
  app:
    handler: index.handler
    memorySize: 128
    url:
      cors:
        allowedOrigins:
          - 'https://tj-the-revolution-6206508ef5c2d17ee4134.webflow.io'
          - 'https://dev2.terpenejourney.com'
        allowCredentials: true
    environment:
        cookieKey: ${self:custom.environment.cookieKey}
        foxy_access_token: ${self:custom.environment.foxy_access_token}
        foxy_client_id: ${self:custom.environment.foxy_client_id}
        foxy_client_secret: ${self:custom.environment.foxy_client_secret}
        foxy_refresh_token: ${self:custom.environment.foxy_refresh_token}
        alpine_api_key: ${self:custom.environment.alpine_api_key}
        dutchie_secret_token: ${self:custom.environment.dutchie_secret_token}
    events:
    - httpApi:
        method: GET
        path: /cors
    - httpApi:
        method: GET
        path: '/cors/{proxy+}'
    - httpApi:
        method: GET
        path: /users
    - httpApi:
        method: GET
        path: '/users/{proxy+}'
    - httpApi:
        method: POST
        path: /users
    - httpApi:
        method: POST
        path: '/users/{proxy+}'
    - httpApi:
        method: PUT
        path: /users/{param}
    - httpApi:
        method: PUT
        path: '/users/{param}/{proxy+}'
    - httpApi:
        method: POST
        path: /users/login
    - httpApi:
        method: POST
        path: '/users/login/{proxy+}'
    - httpApi:
        method: GET
        path: /users/{param}/orders
    - httpApi:
        method: GET
        path: '/users/{param}/orders/{proxy+}'
    - httpApi:
        method: POST
        path: /users/{param1}/orders/{param2}
    - httpApi:
        method: POST
        path: '/users/{param1}/orders/{param2}/{proxy+}'
    - httpApi:
        method: GET
        path: /menu
    - httpApi:
        method: GET
        path: '/menu/{proxy+}'


#plugins:
#  - serverless-domain-manager

#custom:
#  customDomain:
#    domainName: api.terpenejourney.com
#    certificateName: '*.terpenejourney.com'
#    apiType: rest
#    basePath: ''
#    stage: prod
#    endpointType: REGIONAL
