service: dutchie-native
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: prod
  region: us-east-1
  httpApi:
    cors:
      allowedOrigins:
        - 'https://tj-the-revolution-6206508ef5c2d17ee4134.webflow.io'
      allowCredentials: true

functions:
  app:
    handler: index.handler
    memorySize: 128
    url:
      cors:
        allowedOrigins:
          - 'https://tj-the-revolution-6206508ef5c2d17ee4134.webflow.io'
        allowCredentials: true
    events:
    - httpApi:
        method: GET
        path: /cors
    - httpApi:
        method: GET
        path: '/cors/{proxy+}'
    - httpApi:
        method: GET
        path: /users
    - httpApi:
        method: GET
        path: '/users/{proxy+}'
    - httpApi:
        method: POST
        path: /users
    - httpApi:
        method: POST
        path: '/users/{proxy+}'
    - httpApi:
        method: PUT
        path: /users/{param}
    - httpApi:
        method: PUT
        path: '/users/{param}/{proxy+}'
    - httpApi:
        method: POST
        path: /users/login
    - httpApi:
        method: POST
        path: '/users/login/{proxy+}'
    - httpApi:
        method: GET
        path: /users/{param}/orders
    - httpApi:
        method: GET
        path: '/users/{param}/orders/{proxy+}'
    - httpApi:
        method: POST
        path: /users/{param1}/orders/{param2}
    - httpApi:
        method: POST
        path: '/users/{param1}/orders/{param2}/{proxy+}'
    - httpApi:
        method: GET
        path: /menu
    - httpApi:
        method: GET
        path: '/menu/{proxy+}'


#plugins:
#  - serverless-domain-manager

#custom:
#  customDomain:
#    domainName: api.terpenejourney.com
#    certificateName: '*.terpenejourney.com'
#    apiType: rest
#    basePath: ''
#    stage: prod
#    endpointType: REGIONAL
